apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-app
  labels:
    app: fintech-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fintech-app
  template:
    metadata:
      labels:
        app: fintech-app
    spec:
      containers:
        - name: fintech-app
          image: 687222805896.dkr.ecr.ap-south-1.amazonaws.com/web-app:73b0aed9a546c2d398cf0618c6a57508b45607a6
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: fintech-app-env
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
